version: '3.7'
services:
  machine-proxy:
    image: traefik:v2.0-alpine
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    networks:
      - intranet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./certs/:/certs/
      - ~/data/traefik/acme.json:/acme.json
    restart: on-failure

# Create a bridge network called 'intranet',
# which allows communication with other docker-compose setups
networks:
  intranet:
    driver: bridge
