# Global configuration
[global]
  # Do not send anonymous usage for now
  sendAnonymousUsage = false

# Providers discover the services
# that live on your infrastructure (their IP, health, ...)
[providers]
  # Tell traefik to use Docker as a provider
  [providers.docker]
    # Listen to the default docker socket
    endpoint = "unix:///var/run/docker.sock"
    # Manually have containers opt in to being exposed to traefik
    exposedByDefault = false

# Entrypoints listen for incoming traffic (ports, ...)
[entryPoints]
  # Tell traefik to listen to incoming traffic on ports 80
  [entryPoints.web]
    address = ":80"

  # Tell traefik to listen to incoming traffic on ports 443
  [entryPoints.web-secure]
    address = ":443"

# Routers analyse the requests (host, path, headers, SSL, ...)
# Services forward the request to your services (load balancing, ...)

[[tls.certificates]]
  certFile = "/certs/cert.crt"
  keyFile = "/certs/cert.key"

# Middlewares may update the request or make decisions based on the request (authentication, rate limiting, headers, ...)
[http.middlewares]
  [http.middlewares.add-foo-prefix.addPrefix]
    prefix = "/foo"
  [http.middlewares.common.headers]
    # Redirect all non-http call to https
    sslRedirect = true
  # Gzip files
  # [http.middlewares.common.compress]

# Traefik's own API handler, which exposes information such as
# the configuration of all routers, services, middlewares, etc.
# https://docs.traefik.io/v2.0/operations/api/
[api]
  # Dashboard isn't working for beta
  dashboard = false
