# See: https://docs.docker.com/compose/rails/

version: '3.7'

services:
  db:
    image: postgres:11.2-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: .
    volumes:
      - .:/nusmods-rails
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:
